"""name,email,role size changed 

Revision ID: 7002c54d9713
Revises: 665d350b3147
Create Date: 2026-10-03 20:04:00.244555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7002c54d9713'
down_revision: Union[str, Sequence[str], None] = '665d350b3147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application') as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=30),
                   type_=sa.String(length=60),
                   existing_nullable=False)
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(length=30),
                   type_=sa.String(length=50),
                   existing_nullable=False)
        batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(length=40),
                   type_=sa.String(length=30),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('email',
                   existing_type=sa.String(length=30),
                   type_=sa.VARCHAR(length=40),
                   existing_nullable=False)
        batch_op.alter_column('name',
                   existing_type=sa.String(length=50),
                   type_=sa.VARCHAR(length=30),
                   existing_nullable=False)
    with op.batch_alter_table('application') as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.String(length=60),
                   type_=sa.VARCHAR(length=30),
                   existing_nullable=False)
    # ### end Alembic commands ###
